name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PYTHONPATH: '.'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [
          'py27',
          'py35',
          'py36',
          'py37',
          'py38',
        ]
        include:
          - name: 'py27'
            python: '2.7'
          - name: 'py35'
            python: '3.5'
          - name: 'py36'
            python: '3.6'
          - name: 'py37'
            python: '3.7'
          - name: 'py38'
            python: '3.8'
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Test with pytest
      run: |
        pytest --cov-report=xml --cov=sms_toolkit tests